name: Viya Deployment CI

on:
  # schedule:
  #  - cron: "30 * * * *" # Run every half hour
  workflow_dispatch: {} # Added to execute workflow manually

  
jobs:
  ### Work in Progress to automate process of merging upstream with fork upon new commits or releases ###
    sync-upstream: 
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Fork
            uses: actions/checkout@v4
            with:
              fetch-depth: 0 #Fetch all history
          
          - name: Fetch upstream main branch
            run: |
              git remote add upstream https://github.com/sassoftware/viya4-deployment.git
              git fetch upstream main --depth=1 --no-tags --prune 

          - name: Fetch fork origin branch
            run: |
              git remote add upstream https://github.com/rebro24/viya4-deployment.git
              git fetch origin main --depth=1 --no-tags --prune 
    docker:
        runs-on: ubuntu-latest
        steps:
          -
            name: Docker Hub Authentication
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_TOKEN }}
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          -
            name: Build and push
            uses: docker/build-push-action@v6
            with:
                push: true
                tags: rmng10/viya4-deployment:${{ vars.IMAGE_TAG }}
        
